sudo: false
before_script:
- git checkout master
- git status
- openssl aes-256-cbc -K $encrypted_70d73d384ad8_key -iv $encrypted_70d73d384ad8_iv
  -in wohnheimrouter.enc -out ~/.ssh/wohnheimrouter -d
- chmod 600 ~/.ssh/wohnheimrouter
- eval `ssh-agent -s`
- ssh-add -D
- ssh-add ~/.ssh/wohnheimrouter
- git config --global user.name "Nils Strelow"
- git config --global user.email "djnilse@gmail.com"
- git config --global push.default matching
script:
- export PROJECT_HOME="$(pwd)"
- cd $HOME
- mkdir openwrt && cd openwrt
- wget https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64.tar.bz2
- tar -xvjf OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64.tar.bz2
- cd OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64
- make image PROFILE=TLWR841 PACKAGES="base-files busybox dnsmasq dropbear firewall
  fstools hostapd-common iptables iw iwinfo jshn kernel kmod-ath kmod-ath9k kmod-ath9k-common
  kmod-cfg80211 kmod-crypto-ecb kmod-crypto-hash kmod-crypto-manager kmod-crypto-pcompress
  kmod-crypto-sha1 kmod-gpio-button-hotplug kmod-ipt-conntrack kmod-ipt-core kmod-ipt-nat
  kmod-nf-nathelper-extra kmod-iptunnel kmod-ledtrig-usbdev kmod-lib-crc-ccitt kmod-mac80211
  kmod-mppe kmod-nls-base kmod-ppp kmod-pppoe kmod-pppox kmod-pptp kmod-slhc libblobmsg-json
  libc libgcc libip4tc libiwinfo libiwinfo-lua libjson-c libjson-script liblua libnl-tiny
  libubox libubus libubus-lua libuci libuci-lua lua luci luci-app-firewall luci-lib-nixio
  luci-mod-admin-full luci-mod-rpc luci-proto-ppp luci-theme-bootstrap mtd netifd
  odhcpd opkg ppp ppp-mod-pppoe ppp-mod-pptp procd resolveip swconfig uboot-envtools
  ubox ubus ubusd uci uhttpd uhttpd-mod-ubus wpad-mini"
after_success:
- mv $HOME/openwrt/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64/bin/ar71xx/openwrt-ar71xx-generic-tl-wr841-v9-squashfs-factory.bin $PROJECT_HOME/firmwares/openwrt-ar71xx-generic-tl-wr841-v9-squashfs-factory-latest.bin
- mv $HOME/openwrt/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64/bin/ar71xx/openwrt-ar71xx-generic-tl-wr841-v8-squashfs-factory.bin $PROJECT_HOME/firmwares/openwrt-ar71xx-generic-tl-wr841-v8-squashfs-factory-latest.bin
- mv $HOME/openwrt/OpenWrt-ImageBuilder-ar71xx-generic.Linux-x86_64/bin/ar71xx/openwrt-ar71xx-generic-tl-wr841-v10-squashfs-factory.bin $PROJECT_HOME/firmwares/openwrt-ar71xx-generic-tl-wr841-v10-squashfs-factory-latest.bin
- cd $PROJECT_HOME
- git status
- git commit -am "Updated latest v9.x firmware [ci skip]"
- git remote add deploy git@github.com:djnilse/WohnheimRouter.git
- git push deploy master
